# Generated by Django 5.1.15 on 2026-10-08 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(default='v1.0', max_length=50)),
                ('summary', models.TextField()),
                ('why_it_is_a_problem', models.TextField()),
                ('attack_scenario', models.TextField()),
                ('recommended_fix', models.TextField()),
                ('patch_strategy', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.8)),
                ('needs_human_review', models.BooleanField(default=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
