# Generated by Django 5.1.15 on 2026-10-08 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='finding',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='findings.finding'),
        ),
    ]
