# Generated by Django 5.1.15 on 2026-10-08 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ecosystem', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('manifest_path', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='scans.scan')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DependencyVulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vulnerability_id', models.CharField(max_length=100)),
                ('severity', models.CharField(default='MEDIUM', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('fixed_version', models.CharField(blank=True, default='', max_length=100)),
                ('advisory_url', models.URLField(blank=True, default='', max_length=500)),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='findings.dependency')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('rule_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFORMATIONAL', 'Informational')], default='MEDIUM', max_length=20)),
                ('confidence', models.FloatField(default=0.8)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FALSE_POSITIVE', 'False Positive'), ('ACCEPTED_RISK', 'Accepted Risk'), ('FIX_IN_PROGRESS', 'Fix in Progress'), ('FIXED', 'Fixed'), ('REOPENED', 'Reopened')], default='OPEN', max_length=30)),
                ('status_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scans.scan')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FindingEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanner', models.CharField(max_length=50)),
                ('scanner_version', models.CharField(blank=True, default='', max_length=50)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('normalized_evidence', models.TextField(blank=True, default='')),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='findings.finding')),
            ],
        ),
        migrations.CreateModel(
            name='FindingLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1000)),
                ('line_start', models.IntegerField(default=1)),
                ('line_end', models.IntegerField(default=1)),
                ('code_context', models.TextField(blank=True, default='')),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='findings.finding')),
            ],
        ),
    ]
