# Generated by Django 5.1.15 on 2026-10-08 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('html', 'HTML'), ('pdf', 'PDF')], default='json', max_length=20)),
                ('artifact_location', models.CharField(blank=True, default='', max_length=1000)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='scans.scan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
